hydra: 
  run:
    dir: outputs/${data.name}/${experiment}/${net}/${type}/${loss}/${now:%Y-%m-%d_%H%M%S}

experiment: ablation
net: SBCNet
type: Edge

class: multilabels

loss: Dice

defaults:
  - data: litsEdge
  - model: segmodel.yaml

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

# Pytorch lightning trainer's argument
trainer:
  accelerator: 'gpu'
  strategy: 'ddp'
  devices: 1
  precision: 16
  #detect_anomaly: True
  accumulate_grad_batches: 2
  gradient_clip_val: 5
  gradient_clip_algorithm: norm
  log_every_n_steps: 4
  max_epochs: 2000
  track_grad_norm: 2
  #resume_from_checkpoint: /data1/lsx/experiment/paper/tuSeg/last.ckpt
